### ISSUE TITLE
Conversion to HTML is not supported for markdown

### ISSUE THREAD

**Issue by ManikantaMandala** [WnP/vimwiki_markdown#29]
Hi, I'm started using vimwiki recently
I have an issue with with converting markdown code to HTML using :Vimwiki2HTML 

* I had install vimwiki_markdown library with pip using
       
      python3 -m pip install vimwiki-markdown
     
* checked :checkhealth provider.python gives 
    
      Python 3 provider (optional) ~
      - Using: g:python3_host_prog = "/usr/bin/python3"
      - Executable: /usr/bin/python3
      - Python version: 3.10.12
      - pynvim version: 0.5.0
      - OK Latest pynvim is installed.
      
      Python virtualenv ~
      - OK no $VIRTUAL_ENV
  
* and my vimwiki config:

    ``` lua
    return {
        'vimwiki/vimwiki',
        dependencies ={
            'mattn/calendar-vim'
        },
        init = function()
            vim.g.vimwiki_list = {
                {
                    path = '~/vimwiki',
                    template_path = '~/vimwiki/templates/',
                    template_default = 'default',
                    syntax = 'markdown',
                    ext = '.md',
                    path_html = '~/vimwiki/site_html/',
                    custom_wiki2html = 'vimwiki_markdown',
                    template_ext = '.tpl'
                }
            }
        end
    }
   ```
And still I'm getting a conversion to HTML is not supported error
guide me in solving this issue

**Comment by WnP** [comment]
Hi @ManikantaMandala,

Actually my configuration is pretty similar to yours:

```lua
return {
  {
    'vimwiki/vimwiki',
    init = function()
      vim.g.vimwiki_list = {{
        path = '~/Documents/vimwiki',
        template_path = '~/Documents/vimwiki/templates/',
        template_default = 'default',
        syntax = 'markdown',
        ext = '.md',
        path_html = '~/Documents/vimwiki/site_html/',
        custom_wiki2html = 'vimwiki_markdown',
        template_ext = '.html',
      }}
    end,
  },
}
```

Is `vimwiki_markdown` available in your path?

Without an error message or some debug logs it will be difficult to guide you.

**Comment by ManikantaMandala** [comment]
Thank you for your reply!
```vimwiki_markdown``` is in my path
and I'm getting ```IndexError: list index out of range```
Error:
``` bash
$ vimwiki_markdown
Traceback (most recent call last):
  File "/home/manik/.local/bin/vimwiki_markdown", line 8, in <module>
    sys.exit(main())
  File "/home/manik/.local/lib/python3.10/site-packages/vimwiki_markdown.py", line 69, in main
    FORCE = sys.argv[1]  # noqa - not supported
IndexError: list index out of range
```

**Comment by WnP** [comment]
This error message is expected, because you're passing no argument to the command.

BTW that means it is present in your path.

That said I don't know why it vimwiki doesn't use it.
