### ISSUE TITLE
 pip install vimwiki-markdown  failed

### ISSUE THREAD

**Issue by arozehnal** [WnP/vimwiki_markdown#9]
I try to run on AIX ->  pip install vimwiki-markdown  
but this failed

 pip install vimwiki-markdown
Traceback (most recent call last):
  File "/opt/freeware/bin/pip", line 6, in <module>
    from pip._internal.cli.main import main
  File "/opt/freeware/lib/python3.7/site-packages/pip/_internal/__init__.py", line 40, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/opt/freeware/lib/python3.7/site-packages/pip/_internal/cli/autocompletion.py", line 8, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/opt/freeware/lib/python3.7/site-packages/pip/_internal/cli/main_parser.py", line 11, in <module>
    from pip._internal.commands import (
  File "/opt/freeware/lib/python3.7/site-packages/pip/_internal/commands/__init__.py", line 6, in <module>
    from pip._internal.commands.completion import CompletionCommand
  File "/opt/freeware/lib/python3.7/site-packages/pip/_internal/commands/completion.py", line 6, in <module>
    from pip._internal.cli.base_command import Command
  File "/opt/freeware/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 26, in <module>
    from pip._internal.index import PackageFinder
ImportError: cannot import name 'PackageFinder' from 'pip._internal.index' (/opt/freeware/lib/python3.7/site-packages/pip/_internal/index/__init__.py)
`

Any suggestion?

**Comment by WnP** [comment]
@arozehnal can you install any other package using `pip`?

Regarding the traceback you provide it looks like a pip issue

**Comment by arozehnal** [comment]
Yes, you are right, it was pip issue.
Thanks.
